### ISSUE TITLE
Optimal Feature Subset Selection

### ISSUE THREAD

**Issue by stumarcus314** [jeanpauphilet/SubsetSelection.jl#4]
Are you aware of a Julia package that implements an optimal feature subset selection algorithm, such as described here: https://www.ncbi.nlm.nih.gov/pubmed/18579948?

**Comment by jeanpauphilet** [comment]
Hi, 
Thanks for the reference. 
I do not know any implementation of this particular algorithm in Julia. 
I have implemented a different method for the optimal subset selection in regression and classification (https://github.com/jeanpauphilet/SubsetSelectionCIO.jl). Yet, all these methods rely on a branch-and-bound procedure so you would need either a solver (I use CPLEX or Gurobi) or a home-made BB code.
